name: Rapport de bug
description: Pour soumettre un problème fonctionnel (UX/UI, installation de l'environnement, exécution du book, etc.)
title: "[Bug]: "
labels: ["bug"]
assignees:
  - redelman,grgvn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: page
    attributes:
      label: Page
      description: Où le bug s'est-il produit ?
      placeholder: Nom de la page / URL
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      value: "Description du bug"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Quel résultat était attendu ?
      value: "Résultat attendu"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Sur quel navigateur ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Autre
    validations:
      required: true
  - type: dropdown
    id: mobile
    attributes:
      label: Quel format ?
      multiple: true
      options:
        - Mobile
        - Desktop
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs pertinents
      description: Copiez ici tout log pertinent pour aider au debug (la mise en forme shell se fait automatiquement)
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: En soumettant, vous acceptez de suivre notre [Code de conduite](https://github.com/edunumsec2/book/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: J'accepte de suivre le code de conduite.
          required: true
